-- FUNÇÕES DE DATA - https://www.w3schools.com/mySQl/mysql_ref_functions.asp --

-- DATA DO DIA ATUAL (HOJE) --
SELECT CURDATE();

-- HORA ATUAL --
SELECT CURRENT_TIME();

-- DATA E HORA DO MOMENTO -- 
SELECT CURRENT_TIMESTAMP();

-- ANO ATUAL --
SELECT YEAR(CURRENT_TIMESTAMP());

-- DIA ATUAL --
SELECT DAY(CURRENT_TIMESTAMP());

-- MÊS ATUAL --
SELECT MONTH(CURRENT_TIMESTAMP());

-- NOME DO MÊS ATUAL --
SELECT MONTHNAME(CURRENT_TIMESTAMP());

-- DIFERENÇA ENTRE DATAS --
SELECT DATEDIFF(CURRENT_TIMESTAMP(), '2019-01-01') AS RESULTADO;
SELECT DATEDIFF(CURRENT_TIMESTAMP(), '1995-07-16') AS RESULTADO;

-- SUBTRAIR DIAS --
SELECT CURRENT_TIMESTAMP() AS DIA_HOJE,
DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) AS RESULTADO;

-- Usando em tabelas --
SELECT DISTINCT DATA_VENDA,
DAYNAME(DATA_VENDA) AS DIA,
MONTHNAME(DATA_VENDA) AS MES,
YEAR(DATA_VENDA) AS ANO
FROM NOTAS_FISCAIS;

-- Exercício: Crie uma consulta que mostre o nome e a idade atual dos clientes. --
SELECT NOME, TIMESTAMPDIFF (YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS IDADE
FROM  tabela_de_clientes