-- Total de quantidade vendido no mês para cada cliente --
/*
-- Localizar onde está cada campo --
SELECT * FROM notas_fiscais;
SELECT * FROM itens_notas_fiscais;
-- Unir as tabelas --
SELECT * FROM notas_fiscais NF
JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO;
-- Imprimir só o que precisa --
SELECT NF.CPF,NF.DATA_VENDA,INF.QUANTIDADE FROM notas_fiscais NF
JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO;
-- Converter o ano e mês --
SELECT NF.CPF, date_format(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, INF.QUANTIDADE
FROM notas_fiscais NF
JOIN itens_notas_fiscais INF ON NF.NUMERO=INF.NUMERO;
*/
-- VENDAS DE CLIENTES POR MÊS - Agrupando os resultados - TABELA 1 --
SELECT NF.CPF, date_format(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, SUM(INF.QUANTIDADE)
FROM notas_fiscais NF
JOIN itens_notas_fiscais INF ON NF.NUMERO=INF.NUMERO
GROUP BY NF.CPF, date_format(NF.DATA_VENDA, '%Y-%m');

-- Limite de compra por cliente --
-- Localizar onde está cada campo = tabela_de_clientes --
-- Imprimir só o que precisa - TABELA 2 --
SELECT TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA AS QUANTIDADE_LIMITE
FROM tabela_de_clientes TC;

-- UNIR TABELA 1 e TABELA 2 --
SELECT NF.CPF, TC.nome, date_format(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, SUM(INF.QUANTIDADE), MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE
FROM notas_fiscais NF
JOIN itens_notas_fiscais INF ON NF.NUMERO=INF.NUMERO
JOIN tabela_de_clientes TC ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, date_format(NF.DATA_VENDA, '%Y-%m');

-- Especificar a DIFERENÇA (LIMITE - VENDA) --
SELECT X.CPF, X.NOME, X.MES_ANO, X.QUANTIDADE_VENDAS, X.QUANTIDADE_LIMITE
FROM (SELECT NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS, MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')) X;

-- Validar Válidos e Inválidos --
SELECT X.CPF, X.NOME, X.MES_ANO, X.QUANTIDADE_VENDAS, X.QUANTIDADE_LIMITE,
CASE 
WHEN (X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0 THEN 'INVÁLIDA'
ELSE 'VÁLIDA' END AS STATUS_VENDA
FROM (SELECT NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS, MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')) X;

-- Complemente este relatório listando somente os que tiveram vendas inválidas e calculando a diferença entre o limite de venda máximo e o realizado, em percentuais. --
SELECT X.CPF, X.NOME, X.MES_ANO, X.QUANTIDADE_VENDAS, X.QUANTIDADE_LIMITE,
CASE 
WHEN (X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0 THEN 'INVÁLIDA'
ELSE 'VÁLIDA' END AS STATUS_VENDA, (1 - (X.QUANTIDADE_LIMITE/X.QUANTIDADE_VENDAS)) * 100 AS PERCENTUAL
FROM (SELECT NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS, MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')) X
WHERE (X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0;



